#+TITLE: Invenio Bitten
#+AUTHOR: Tibor Simko
#+EMAIL: tibor.simko@cern.ch
#+DATE: <2011-06-03 Fri>
#+DESCRIPTION: Invenio Bitten recipe and client setup.
#+KEYWORDS: invenio, trac, bitten
#+LANGUAGE: en

* About invenio-bitten

=invenio-bitten= repository contains [[http://bitten.edgewall.org][Bitten]] recipe and client tools
used to set up [[http://invenio-software.org/][Invenio]] continuous integration infrastructure for [[http://trac.edgewall.org][Trac]].

* Contents

- invenio-bitten-recipe.xml :: Invenio Bitten recipe
- invenio-bitten-client :: helper script for Invenio Bitten client machines

* Installation

** Setting up Bitten server

=invenio-bitten-recipe.xml= is to be used in Invenio Trac Bitten
configuration.  This part of installation is not covered here; see the
usual Bitten documentation.

** Setting up Bitten clients

Executable =invenio-bitten-client= is to be put to =/usr/bin= on
Invenio Bitten client machines.

Moreover, Invenio Bitten clients need to have special sudo rights to
run certain commands as user =nobody= in order to invoke LibreOffice
file conversions.  This can be set up as:

- on Debian GNU/Linux:

  :  $ sudo cat /etc/sudoers.d/www-data
  :  www-data ALL=(nobody) NOPASSWD: /opt/invenio/bin/inveniounoconv, (root) NOPASSWD: /usr/bin/invenio-bitten-client

- on SLC5 (aka RHEL5):

  : $ sudo tail -1 /etc/sudoers
  : apache ALL=(ALL) NOPASSWD: /usr/sbin/apachectl, (nobody) NOPASSWD: /opt/invenio/bin/inveniounoconv, (root) NOPASSWD: /usr/bin/invenio-bitten-client

** Running Bitten clients

Invenio Bitten clients can then be run as follows:

- on Debian GNU/Linux:

  : $ sudo -u www-data bitten-slave http://invenio-software.org/builds

- on SLC5 (aka RHEL5):

  : $ sudo -u apache bitten-slave http://invenio-software.org/builds

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see [[http://www.gnu.org/licenses/]].

* See also

- [[http://invenio-software.org/][Invenio]]
- [[http://bitten.edgewall.org][Bitten]]
- [[http://trac.edgewall.org][Trac]]
